version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./dist s3://quick-bite/
      - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./dist/index.html s3://quick-bite/
      - aws cloudfront create-invalidation --distribution-id EUUJTFBUFDDY --paths /
artifacts:
  files:
    - "dist/*"
    - "dist/**/*"