version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd backend
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Zipping application files after build...
      - zip -r application.zip * -x "*.git*" "node_modules/*" "test/*"
      - mv application.zip ../
      - aws s3 cp ../application.zip s3://skip-clone/deployment/backend/application.zip
      - npm run build
artifacts:
  files:
    - 'application.zip'
